// 05.react/02.react组件/01.react-cli/src/components/List/index.jsx
import React, { Component } from "react";
import PropTypes from "prop-types";
import axios from "axios";

export default class List extends Component {
  static propTypes = {
    searchName: PropTypes.string.isRequired,
  };

  state = {
    isFirstView: true,
    isLoading: false,
    users: null,
  };

  UNSAFE_componentWillReceiveProps(nextProps) {
    this.setState({
      isFirstView: false,
      isLoading: true,
    });
    // 发送请求
    // axios.get(`http://localhost:9527?searchName=${nextProps.searchName}`);
    axios
      .get(`http://localhost:9527`, {
        params: {
          searchName: nextProps.searchName,
        },
      })
      .then((res) => {
        // 请求成功
        this.setState({
          isLoading: false,
          users: res.data.items.map((item) => {
            return {
              name: item.login,
              url: item.html_url,
              img: item.avatar_url,
              id: item.id,
            };
          }),
        });
      })
      .catch((err) => {
        console.dir(err);
        // 请求失败
        this.setState({
          isLoading: false,
        });
        alert("请求失败~");
      });
  }

  render() {
    const { isFirstView, isLoading, users } = this.state;

    if (isFirstView) {
      return <h1>enter name to search</h1>;
    } else if (isLoading) {
      return <h1>loading...</h1>;
    }

    return (
      <div className="row">
        {users.map((user) => {
          return (
            <div className="card" key={user.id}>
              <a href={user.url} target="_blank" rel="noopener noreferrer">
                <img src={user.img} style={{ width: 100 }} alt="用户头像" />
              </a>
              <p className="card-text">{user.name}</p>
            </div>
          );
        })}
      </div>
    );
  }
}

// 04.vue/03.VueComponent/07.VueAjax/src/components/List/index.vue
<template>
  <div>
    <h1 v-if="isFirstView">请输入要搜索的内容</h1>
    <h1 v-else-if="isLoading">loading...</h1>
    <div class="row" v-else-if="users">
      <div class="card" v-for="user in users" :key="user.id">
        <a :href="user.html_url" target="_blank">
          <img :src="user.avatar_url" style="width: 100px" />
        </a>
        <p class="card-text">{{ user.login }}</p>
      </div>
    </div>
    <p v-else>{{error}}</p>
  </div>
</template>

<script>
import axios from "axios";

export default {
  data() {
    return {
      isFirstView: true,
      isLoading: false,
      users: null,
      error: "",
    };
  },
  methods: {
    search(searchName) {
      // console.log(searchName);
      // 发送请求之前，先要切换成loading
      this.isFirstView = false;
      this.isLoading = true;
      // 发送ajax请求
      axios
        .get(`http://localhost:9527/api?q=${searchName}`)
        .then((res) => {
          this.isLoading = false;
          this.users = res.data.items;
        })
        .catch((err) => {
          this.isLoading = false;
          this.users = null;
          this.error = "网络出现故障...";
        });
    },
  },
  mounted() {
    this.$bus.$on("search", this.search);
  },
  beforeDestroy() {
    this.$bus.$off("search", this.search);
  },
};
</script>

<style scoped></style>
