// 05.react/02.react组件/01.react-cli/src/pages/Home/index.jsx
import React, { Component } from "react";

import { NavLink, Route, Redirect, Switch } from "react-router-dom";

import News from "../News";
import Messages from "../Messages";

export default class Home extends Component {
  
  render() {
    return (
      <div>
        <h2>Home...</h2>
        <ul className="nav nav-tabs">
          <li>
            <NavLink to="/home/news">News</NavLink>
          </li>
          <li>
            <NavLink to="/home/messages">Messages</NavLink>
          </li>
        </ul>
        <Switch>
          <Route path="/home/news" component={News} />
          <Route path="/home/messages" component={Messages} />
          <Redirect to="/home/news" />
        </Switch>
      </div>
    );
  }
}

// 04.vue/03.VueComponent/09.VueRouter/src/pages/home/index.vue
<template>
  <div>
    <h1>home....</h1>
    <ul>
      <li><router-link to="/home/news">news</router-link></li>
      <li>
        <router-link to="/home/messages">messages</router-link>
      </li>
    </ul>
    <!-- 显示路由组件 -->
    <router-view></router-view>
  </div>
</template>

<script>
export default {};
</script>

<style scoped></style>
