// 04.vue/03.VueComponent/07.VueAjax/src/components/Search/index.vue
<template>
  <section class="jumbotron">
    <h3 class="jumbotron-heading">Search Github Users</h3>
    <div>
      <input
        type="text"
        placeholder="enter the name you search"
        v-model="searchName"
      />
      <button @click="search">Search</button>
    </div>
  </section>
</template>

<script>
export default {
  data() {
    return {
      searchName: ''
    }
  },
  methods: {
    search() {
      const searchName = this.searchName.trim();
      if (!searchName) {
        alert('请输入要搜索的内容~');
        return;
      }
      this.$bus.$emit('search', searchName);
    }
  }
};
</script>

<style scoped></style>

// 05.react/02.react组件/01.react-cli/src/components/Search/index.jsx
import React, { Component } from "react";
import PropTypes from "prop-types";

export default class Search extends Component {
  static propTypes = {
    getSearchName: PropTypes.func.isRequired,
  };

  state = {
    searchName: "",
  };

  handleChange = (e) => {
    this.setState({
      searchName: e.target.value.trim(),
    });
  };

  handleClick = () => {
    const { searchName } = this.state;

    if (!searchName) {
      alert("请输入搜索名称~");
      return;
    }

    this.props.getSearchName(searchName);
  };

  render() {
    return (
      <section className="jumbotron">
        <h3 className="jumbotron-heading">Search Github Users</h3>
        <div>
          <input
            type="text"
            placeholder="enter the name you search"
            onChange={this.handleChange}
          />
          <button onClick={this.handleClick}>Search</button>
        </div>
      </section>
    );
  }
}
