// 04.vue/03.VueComponent/09.VueRouter/src/pages/messages/index.vue
<template>
  <div>
    messages....
    <ul>
      <li v-for="message in messages" :key="message.id">
        <router-link :to="`/home/messages/detail/${message.id}`">{{
          message.content
        }}</router-link>
      </li>
    </ul>
    <router-view></router-view>
  </div>
</template>

<script>
export default {
  data() {
    return {
      messages: [],
    };
  },
  created() {
    setTimeout(() => {
      // 模拟请求的结果
      const messages = [
        { id: 1, content: "message001" },
        { id: 3, content: "message003" },
        { id: 5, content: "message005" },
      ];
      // 必须修改data中数据才能更新
      this.messages = messages;
    }, 1000);
  },
};
</script>

<style scoped></style>

// 05.react/02.react组件/01.react-cli/src/pages/Messages/index.jsx
import React, { Component } from "react";
import { Link, Route } from "react-router-dom";

import Detail from "../Detail";

export default class Messages extends Component {
  render() {
    return (
      <div>
        Messages...
        <ul>
          <li>
            <Link to="/home/messages/1?name=jack">Message 001</Link>
          </li>
          <li>
            <Link to="/home/messages/3">Message 003</Link>
          </li>
          <li>
            <Link to="/home/messages/5">Message 005</Link>
          </li>
        </ul>
        <Route path="/home/messages/:id" component={Detail} />
      </div>
    );
  }
}
